### ISSUE TITLE
Implementation is vulnerable to side channel attacks

### ISSUE THREAD

**Issue by FlorianB-DE** [dhuertas/AES#14]
Since your implementation uses GF2^8 look up tables, it is vulnerable to side channel attacks on CPU cache.
See https://github.com/ECLab-ITU/Cache-Side-Channel-Attacks/blob/master/AES%20-%20HalfKey/Flush%2BReload/Readme.md

**Comment by FlorianB-DE** [comment]
This is for some parts a joke but on the other hand, people actually wanting to implement AES should know, that this is a real vulnerability.

**Comment by dhuertas** [comment]
Hi @FlorianB-DE. Thanks for bringing the vulnerability to my attention. When I first wrote the GF look-up table I was oblivious that such attack would exist.

As you kinda suggested, I expect nobody to take this code for any serious project. However, as the repo stands, it might be better to add a comment on the code itself - or perhaps a message section in the README.md file - so that future readers are also made aware of the vulnerability introduced by the look-up table approach.

Are you open to do a PR? Otherwise I will add the comments myself on my spare time.

Cheers!
